// Package store owns database connectivity and schema migrations. Query code
// generated by sqlc is added here in later phases.
package store

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"github.com/pressly/goose/v3/lock"

	"github.com/ininia/scanx/internal/secret"
	"github.com/ininia/scanx/migrations"
)

// Open creates a connection pool and verifies connectivity.
func Open(ctx context.Context, dsn secret.Secret) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(dsn.Reveal())
	if err != nil {
		// pgx errors may include the DSN; keep the message generic.
		return nil, errors.New("store: invalid database URL")
	}
	cfg.MaxConnLifetime = time.Hour
	cfg.MaxConnIdleTime = 15 * time.Minute
	cfg.HealthCheckPeriod = 30 * time.Second
	if cfg.ConnConfig.ConnectTimeout == 0 {
		cfg.ConnConfig.ConnectTimeout = 10 * time.Second
	}
	if cfg.ConnConfig.RuntimeParams == nil {
		cfg.ConnConfig.RuntimeParams = map[string]string{}
	}
	cfg.ConnConfig.RuntimeParams["application_name"] = "scanx"
	cfg.ConnConfig.RuntimeParams["statement_timeout"] = "30000"

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("store: create pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return pool, nil
}

// newProvider builds a goose provider on top of pool. The provider must be
// closed by the caller (which closes the *sql.DB wrapper, not the pool).
func newProvider(pool *pgxpool.Pool, withLock bool) (*goose.Provider, error) {
	var opts []goose.ProviderOption
	if withLock {
		locker, err := lock.NewPostgresSessionLocker()
		if err != nil {
			return nil, fmt.Errorf("store: session locker: %w", err)
		}
		opts = append(opts, goose.WithSessionLocker(locker))
	}
	p, err := goose.NewProvider(goose.DialectPostgres, stdlib.OpenDBFromPool(pool), migrations.FS, opts...)
	if err != nil {
		return nil, fmt.Errorf("store: goose provider: %w", err)
	}
	return p, nil
}

// Migrate applies all pending migrations using the schema-owner connection.
// A Postgres advisory lock makes concurrent starts (several servers) safe.
func Migrate(ctx context.Context, adminDSN secret.Secret, log *slog.Logger) error {
	pool, err := Open(ctx, adminDSN)
	if err != nil {
		return err
	}
	defer pool.Close()

	p, err := newProvider(pool, true)
	if err != nil {
		return err
	}
	defer func() { _ = p.Close() }()

	results, err := p.Up(ctx)
	for _, r := range results {
		log.InfoContext(ctx, "migration applied",
			"version", r.Source.Version, "duration_ms", r.Duration.Milliseconds())
	}
	if err != nil {
		return fmt.Errorf("store: migrate up: %w", err)
	}
	return nil
}

// MigrationsCurrent returns an error if the database schema is behind the
// migrations compiled into this binary. Used by the readiness probe.
func MigrationsCurrent(ctx context.Context, pool *pgxpool.Pool) error {
	p, err := newProvider(pool, false)
	if err != nil {
		return err
	}
	defer func() { _ = p.Close() }()
	current, target, err := p.GetVersions(ctx)
	if err != nil {
		return fmt.Errorf("store: migration versions: %w", err)
	}
	if current < target {
		return fmt.Errorf("store: schema version %d behind %d", current, target)
	}
	return nil
}
