// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	UserID      *uuid.UUID
	ProjectID   *uuid.UUID
	Name        string
	TokenPrefix string
	TokenHash   []byte
	Scopes      []string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type AuditLog struct {
	ID         uuid.UUID
	OrgID      *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	TargetType string
	TargetID   string
	Ip         string
	Metadata   json.RawMessage
	CreatedAt  time.Time
}

type InstanceSetting struct {
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type Invitation struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       string
	TokenHash  []byte
	InvitedBy  *uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

type Membership struct {
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Settings  json.RawMessage
	CreatedAt time.Time
}

type Project struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Name         string
	Slug         string
	RepoUrl      string
	Provider     string
	AuthMode     string
	Branches     []string
	Settings     json.RawMessage
	ScheduleCron *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ArchivedAt   *time.Time
}

type Session struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	TokenHash   []byte
	MfaPending  bool
	ActiveOrgID *uuid.UUID
	Ip          string
	UserAgent   string
	CreatedAt   time.Time
	LastSeenAt  time.Time
	ExpiresAt   time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	Name          string
	PasswordHash  string
	TotpSecretEnc []byte
	TotpNonce     []byte
	TotpEnabled   bool
	IsSuperadmin  bool
	LockedUntil   *time.Time
	FailedLogins  int32
	CreatedAt     time.Time
	LastLoginAt   *time.Time
	Locale        string
}
