// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE invitations SET accepted_at = now() WHERE id = $1 AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addMember = `-- name: AddMember :exec
INSERT INTO memberships (org_id, user_id, role) VALUES ($1, $2, $3)
`

type AddMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations (id, org_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, lower($7), $3, $4, $5, $6)
`

type CreateInvitationParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Role      string
	TokenHash []byte
	InvitedBy *uuid.UUID
	ExpiresAt time.Time
	Email     string
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.Exec(ctx, createInvitation,
		arg.ID,
		arg.OrgID,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.Email,
	)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organizations (id, name, slug) VALUES ($1, $2, $3) RETURNING id, name, slug, settings, created_at
`

type CreateOrgParams struct {
	ID   uuid.UUID
	Name string
	Slug string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM invitations WHERE org_id = $1 AND id = $2
`

type DeleteInvitationParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
SELECT org_id, user_id, role, created_at FROM memberships WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, slug, settings, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, settings, created_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listAllOrgs = `-- name: ListAllOrgs :many
SELECT o.id, o.name, o.slug, o.settings, o.created_at, (SELECT count(*) FROM memberships m WHERE m.org_id = o.id) AS member_count
FROM organizations o ORDER BY o.name LIMIT $1 OFFSET $2
`

type ListAllOrgsParams struct {
	Limit  int32
	Offset int32
}

type ListAllOrgsRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Settings    json.RawMessage
	CreatedAt   time.Time
	MemberCount int64
}

func (q *Queries) ListAllOrgs(ctx context.Context, arg ListAllOrgsParams) ([]ListAllOrgsRow, error) {
	rows, err := q.db.Query(ctx, listAllOrgs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrgsRow{}
	for rows.Next() {
		var i ListAllOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, org_id, email, role, invited_by, expires_at, accepted_at, created_at
FROM invitations WHERE org_id = $1 AND accepted_at IS NULL ORDER BY created_at DESC
`

type ListInvitationsRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       string
	InvitedBy  *uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

func (q *Queries) ListInvitations(ctx context.Context, orgID uuid.UUID) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.org_id, m.user_id, m.role, m.created_at, u.email, u.name, u.totp_enabled, u.last_login_at
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 ORDER BY u.email
`

type ListMembersRow struct {
	OrgID       uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
	Email       string
	Name        string
	TotpEnabled bool
	LastLoginAt *time.Time
}

func (q *Queries) ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.TotpEnabled,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.slug, o.settings, o.created_at, m.role
FROM organizations o JOIN memberships m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

type ListOrgsForUserRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Settings  json.RawMessage
	CreatedAt time.Time
	Role      string
}

// RLS limits rows to orgs the current user belongs to (or all for superadmin
// when the superadmin flag is set on the transaction).
func (q *Queries) ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsForUserRow{}
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupInvitation = `-- name: LookupInvitation :one
SELECT l.id::uuid AS id, l.org_id::uuid AS org_id, l.email::text AS email, l.role::text AS role,
       l.expires_at::timestamptz AS expires_at,
       coalesce(l.accepted_at, '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS accepted_at, l.org_name::text AS org_name
FROM scanx_lookup_invitation($1::bytea) AS l
`

type LookupInvitationRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       string
	ExpiresAt  time.Time
	AcceptedAt time.Time
	OrgName    string
}

func (q *Queries) LookupInvitation(ctx context.Context, tokenHash []byte) (LookupInvitationRow, error) {
	row := q.db.QueryRow(ctx, lookupInvitation, tokenHash)
	var i LookupInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.OrgName,
	)
	return i, err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM memberships WHERE org_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :execrows
UPDATE memberships SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberRole, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE organizations SET name = $2 WHERE id = $1 RETURNING id, name, slug, settings, created_at
`

type UpdateOrgParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
