// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveProject = `-- name: ArchiveProject :execrows
UPDATE projects SET archived_at = now(), updated_at = now() WHERE org_id = $1 AND id = $2 AND archived_at IS NULL
`

type ArchiveProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveProject, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
WHERE org_id = $1 AND ($2::bool OR archived_at IS NULL)
`

type CountProjectsParams struct {
	OrgID           uuid.UUID
	IncludeArchived bool
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.OrgID, arg.IncludeArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, name, slug, repo_url, provider, auth_mode, branches, schedule_cron)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, slug, repo_url, provider, auth_mode, branches, settings, schedule_cron, created_at, updated_at, archived_at, webhook_secret_enc, webhook_secret_nonce, fail_on, scan_history, sast_timeout_minutes, push_scope
`

type CreateProjectParams struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Name         string
	Slug         string
	RepoUrl      string
	Provider     string
	AuthMode     string
	Branches     []string
	ScheduleCron *string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.RepoUrl,
		arg.Provider,
		arg.AuthMode,
		arg.Branches,
		arg.ScheduleCron,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.Provider,
		&i.AuthMode,
		&i.Branches,
		&i.Settings,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.WebhookSecretEnc,
		&i.WebhookSecretNonce,
		&i.FailOn,
		&i.ScanHistory,
		&i.SastTimeoutMinutes,
		&i.PushScope,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE org_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, name, slug, repo_url, provider, auth_mode, branches, settings, schedule_cron, created_at, updated_at, archived_at, webhook_secret_enc, webhook_secret_nonce, fail_on, scan_history, sast_timeout_minutes, push_scope FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.Provider,
		&i.AuthMode,
		&i.Branches,
		&i.Settings,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.WebhookSecretEnc,
		&i.WebhookSecretNonce,
		&i.FailOn,
		&i.ScanHistory,
		&i.SastTimeoutMinutes,
		&i.PushScope,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, name, slug, repo_url, provider, auth_mode, branches, settings, schedule_cron, created_at, updated_at, archived_at, webhook_secret_enc, webhook_secret_nonce, fail_on, scan_history, sast_timeout_minutes, push_scope FROM projects WHERE org_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrgID uuid.UUID
	Slug  string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.Provider,
		&i.AuthMode,
		&i.Branches,
		&i.Settings,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.WebhookSecretEnc,
		&i.WebhookSecretNonce,
		&i.FailOn,
		&i.ScanHistory,
		&i.SastTimeoutMinutes,
		&i.PushScope,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, slug, repo_url, provider, auth_mode, branches, settings, schedule_cron, created_at, updated_at, archived_at, webhook_secret_enc, webhook_secret_nonce, fail_on, scan_history, sast_timeout_minutes, push_scope FROM projects
WHERE org_id = $1 AND ($4::bool OR archived_at IS NULL)
ORDER BY name LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	OrgID           uuid.UUID
	Limit           int32
	Offset          int32
	IncludeArchived bool
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.RepoUrl,
			&i.Provider,
			&i.AuthMode,
			&i.Branches,
			&i.Settings,
			&i.ScheduleCron,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.WebhookSecretEnc,
			&i.WebhookSecretNonce,
			&i.FailOn,
			&i.ScanHistory,
			&i.SastTimeoutMinutes,
			&i.PushScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, repo_url = $4, provider = $5, branches = $6, schedule_cron = $7, updated_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, slug, repo_url, provider, auth_mode, branches, settings, schedule_cron, created_at, updated_at, archived_at, webhook_secret_enc, webhook_secret_nonce, fail_on, scan_history, sast_timeout_minutes, push_scope
`

type UpdateProjectParams struct {
	OrgID        uuid.UUID
	ID           uuid.UUID
	Name         string
	RepoUrl      string
	Provider     string
	Branches     []string
	ScheduleCron *string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Provider,
		arg.Branches,
		arg.ScheduleCron,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.Provider,
		&i.AuthMode,
		&i.Branches,
		&i.Settings,
		&i.ScheduleCron,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.WebhookSecretEnc,
		&i.WebhookSecretNonce,
		&i.FailOn,
		&i.ScanHistory,
		&i.SastTimeoutMinutes,
		&i.PushScope,
	)
	return i, err
}
