// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeManualScan = `-- name: ActiveManualScan :one
SELECT id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author, status, status_reason, partial, summary, gate_result, score, new_issues, fixed_issues, queued_at, started_at, finished_at, cleaned_at FROM scans WHERE org_id = $1 AND project_id = $2 AND branch = $3 AND status = 'queued' AND commit_sha = ''
LIMIT 1
`

type ActiveManualScanParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Branch    string
}

func (q *Queries) ActiveManualScan(ctx context.Context, arg ActiveManualScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, activeManualScan, arg.OrgID, arg.ProjectID, arg.Branch)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Branch,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.Status,
		&i.StatusReason,
		&i.Partial,
		&i.Summary,
		&i.GateResult,
		&i.Score,
		&i.NewIssues,
		&i.FixedIssues,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CleanedAt,
	)
	return i, err
}

const cancelScan = `-- name: CancelScan :execrows
UPDATE scans SET status = 'canceled', finished_at = now()
WHERE org_id = $1 AND id = $2 AND status IN ('queued', 'cloning', 'scanning', 'reporting')
`

type CancelScanParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) CancelScan(ctx context.Context, arg CancelScanParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelScan, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET status = 'running', locked_by = $1, locked_until = $2,
    attempts = attempts + 1, started_at = coalesce(started_at, now())
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.status = 'queued' OR (j.status = 'running' AND j.locked_until < now() AND j.attempts < 3)
    ORDER BY j.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, org_id, kind, project_id, scan_id, status, result, error, attempts, locked_by, locked_until, created_at, started_at, finished_at
`

type ClaimJobParams struct {
	Worker      string
	LockedUntil *time.Time
}

// Takes the oldest queued job, or a running job whose worker died (lock
// expired) if it has attempts left.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.Worker, arg.LockedUntil)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.ProjectID,
		&i.ScanID,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Attempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countOpenIssues = `-- name: CountOpenIssues :many
SELECT severity, count(*) AS n FROM issues WHERE org_id = $1 AND status = 'open' GROUP BY severity
`

type CountOpenIssuesRow struct {
	Severity string
	N        int64
}

func (q *Queries) CountOpenIssues(ctx context.Context, orgID uuid.UUID) ([]CountOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, countOpenIssues, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenIssuesRow{}
	for rows.Next() {
		var i CountOpenIssuesRow
		if err := rows.Scan(&i.Severity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenIssuesByProject = `-- name: CountOpenIssuesByProject :many
SELECT project_id, severity, count(*) AS n FROM issues WHERE org_id = $1 AND status = 'open'
GROUP BY project_id, severity
`

type CountOpenIssuesByProjectRow struct {
	ProjectID uuid.UUID
	Severity  string
	N         int64
}

func (q *Queries) CountOpenIssuesByProject(ctx context.Context, orgID uuid.UUID) ([]CountOpenIssuesByProjectRow, error) {
	rows, err := q.db.Query(ctx, countOpenIssuesByProject, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenIssuesByProjectRow{}
	for rows.Next() {
		var i CountOpenIssuesByProjectRow
		if err := rows.Scan(&i.ProjectID, &i.Severity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countQueuedJobs = `-- name: CountQueuedJobs :one
SELECT count(*) FROM jobs WHERE status IN ('queued', 'running')
`

func (q *Queries) CountQueuedJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQueuedJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :exec

INSERT INTO notification_channels (id, org_id, kind, name, target_enc, nonce, events)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateNotificationChannelParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Kind      string
	Name      string
	TargetEnc []byte
	Nonce     []byte
	Events    []string
}

// ---------- notifications ----------
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, createNotificationChannel,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Name,
		arg.TargetEnc,
		arg.Nonce,
		arg.Events,
	)
	return err
}

const createSSHKey = `-- name: CreateSSHKey :exec

INSERT INTO ssh_keys (id, org_id, project_id, public_key, fingerprint, private_key_enc, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSSHKeyParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ProjectID     uuid.UUID
	PublicKey     string
	Fingerprint   string
	PrivateKeyEnc []byte
	Nonce         []byte
}

// ---------- deploy keys ----------
func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) error {
	_, err := q.db.Exec(ctx, createSSHKey,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.PublicKey,
		arg.Fingerprint,
		arg.PrivateKeyEnc,
		arg.Nonce,
	)
	return err
}

const createScan = `-- name: CreateScan :one

INSERT INTO scans (id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, branch, commit_sha)
    WHERE status IN ('queued', 'cloning', 'scanning', 'reporting') AND commit_sha <> '' DO NOTHING
RETURNING id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author, status, status_reason, partial, summary, gate_result, score, new_issues, fixed_issues, queued_at, started_at, finished_at, cleaned_at
`

type CreateScanParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ProjectID     uuid.UUID
	Trigger       string
	TriggeredBy   *uuid.UUID
	Branch        string
	CommitSha     string
	CommitMessage string
	CommitAuthor  string
}

// ---------- scans ----------
func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Trigger,
		arg.TriggeredBy,
		arg.Branch,
		arg.CommitSha,
		arg.CommitMessage,
		arg.CommitAuthor,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Branch,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.Status,
		&i.StatusReason,
		&i.Partial,
		&i.Summary,
		&i.GateResult,
		&i.Score,
		&i.NewIssues,
		&i.FixedIssues,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CleanedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE org_id = $1 AND id = $2
`

type DeleteNotificationChannelParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldSSHKeys = `-- name: DeleteOldSSHKeys :execrows
DELETE FROM ssh_keys WHERE status = 'retiring' AND retired_at < now() - interval '7 days'
`

func (q *Queries) DeleteOldSSHKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSSHKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :exec

INSERT INTO jobs (id, org_id, kind, project_id, scan_id) VALUES ($1, $2, $3, $4, $5)
`

type EnqueueJobParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Kind      string
	ProjectID uuid.UUID
	ScanID    *uuid.UUID
}

// ---------- jobs ----------
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.ProjectID,
		arg.ScanID,
	)
	return err
}

const extendJobLock = `-- name: ExtendJobLock :exec
UPDATE jobs SET locked_until = $2 WHERE id = $1 AND status = 'running'
`

type ExtendJobLockParams struct {
	ID          uuid.UUID
	LockedUntil *time.Time
}

func (q *Queries) ExtendJobLock(ctx context.Context, arg ExtendJobLockParams) error {
	_, err := q.db.Exec(ctx, extendJobLock, arg.ID, arg.LockedUntil)
	return err
}

const failStaleJobs = `-- name: FailStaleJobs :many
UPDATE jobs SET status = 'failed', error = 'worker stopped responding', finished_at = now()
WHERE status = 'running' AND locked_until < now() AND attempts >= 3
RETURNING id, scan_id
`

type FailStaleJobsRow struct {
	ID     uuid.UUID
	ScanID *uuid.UUID
}

func (q *Queries) FailStaleJobs(ctx context.Context) ([]FailStaleJobsRow, error) {
	rows, err := q.db.Query(ctx, failStaleJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailStaleJobsRow{}
	for rows.Next() {
		var i FailStaleJobsRow
		if err := rows.Scan(&i.ID, &i.ScanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET status = $2, result = $3, error = $4, finished_at = now(), locked_until = NULL WHERE id = $1
`

type FinishJobParams struct {
	ID     uuid.UUID
	Status string
	Result json.RawMessage
	Error  string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	return err
}

const finishScan = `-- name: FinishScan :exec
UPDATE scans SET status = $2, status_reason = $3, partial = $4, summary = $5, gate_result = $6, score = $7,
    new_issues = $8, fixed_issues = $9, finished_at = now(), cleaned_at = now()
WHERE id = $1
`

type FinishScanParams struct {
	ID           uuid.UUID
	Status       string
	StatusReason string
	Partial      bool
	Summary      json.RawMessage
	GateResult   *string
	Score        *int32
	NewIssues    int32
	FixedIssues  int32
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.db.Exec(ctx, finishScan,
		arg.ID,
		arg.Status,
		arg.StatusReason,
		arg.Partial,
		arg.Summary,
		arg.GateResult,
		arg.Score,
		arg.NewIssues,
		arg.FixedIssues,
	)
	return err
}

const getActiveSSHKey = `-- name: GetActiveSSHKey :one
SELECT id, org_id, project_id, public_key, fingerprint, private_key_enc, nonce, status, created_at, retired_at FROM ssh_keys WHERE org_id = $1 AND project_id = $2 AND status = 'active'
`

type GetActiveSSHKeyParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetActiveSSHKey(ctx context.Context, arg GetActiveSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, getActiveSSHKey, arg.OrgID, arg.ProjectID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.PrivateKeyEnc,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, org_id, project_id, fingerprint, category, severity, title, rule_id, file, start_line, cwe, cve, sources, status, status_reason, detail, first_seen_scan_id, last_seen_scan_id, fixed_in_scan_id, created_at, updated_at FROM issues WHERE org_id = $1 AND id = $2
`

type GetIssueParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.OrgID, arg.ID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Fingerprint,
		&i.Category,
		&i.Severity,
		&i.Title,
		&i.RuleID,
		&i.File,
		&i.StartLine,
		&i.Cwe,
		&i.Cve,
		&i.Sources,
		&i.Status,
		&i.StatusReason,
		&i.Detail,
		&i.FirstSeenScanID,
		&i.LastSeenScanID,
		&i.FixedInScanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, org_id, kind, project_id, scan_id, status, result, error, attempts, locked_by, locked_until, created_at, started_at, finished_at FROM jobs WHERE org_id = $1 AND id = $2
`

type GetJobParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.OrgID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.ProjectID,
		&i.ScanID,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Attempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, org_id, kind, name, target_enc, nonce, events, created_at FROM notification_channels WHERE org_id = $1 AND id = $2
`

type GetNotificationChannelParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.OrgID, arg.ID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Name,
		&i.TargetEnc,
		&i.Nonce,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT content_gz FROM reports WHERE org_id = $1 AND scan_id = $2 AND format = $3
`

type GetReportParams struct {
	OrgID  uuid.UUID
	ScanID uuid.UUID
	Format string
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReport, arg.OrgID, arg.ScanID, arg.Format)
	var content_gz []byte
	err := row.Scan(&content_gz)
	return content_gz, err
}

const getScan = `-- name: GetScan :one
SELECT id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author, status, status_reason, partial, summary, gate_result, score, new_issues, fixed_issues, queued_at, started_at, finished_at, cleaned_at FROM scans WHERE org_id = $1 AND id = $2
`

type GetScanParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetScan(ctx context.Context, arg GetScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, arg.OrgID, arg.ID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Branch,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.Status,
		&i.StatusReason,
		&i.Partial,
		&i.Summary,
		&i.GateResult,
		&i.Score,
		&i.NewIssues,
		&i.FixedIssues,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getScanByID = `-- name: GetScanByID :one
SELECT id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author, status, status_reason, partial, summary, gate_result, score, new_issues, fixed_issues, queued_at, started_at, finished_at, cleaned_at FROM scans WHERE id = $1
`

func (q *Queries) GetScanByID(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScanByID, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Branch,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.Status,
		&i.StatusReason,
		&i.Partial,
		&i.Summary,
		&i.GateResult,
		&i.Score,
		&i.NewIssues,
		&i.FixedIssues,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CleanedAt,
	)
	return i, err
}

const insertIssueEvent = `-- name: InsertIssueEvent :exec
INSERT INTO issue_events (id, org_id, issue_id, user_id, kind, from_value, to_value, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertIssueEventParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	IssueID   uuid.UUID
	UserID    *uuid.UUID
	Kind      string
	FromValue string
	ToValue   string
	Comment   string
}

func (q *Queries) InsertIssueEvent(ctx context.Context, arg InsertIssueEventParams) error {
	_, err := q.db.Exec(ctx, insertIssueEvent,
		arg.ID,
		arg.OrgID,
		arg.IssueID,
		arg.UserID,
		arg.Kind,
		arg.FromValue,
		arg.ToValue,
		arg.Comment,
	)
	return err
}

const insertReport = `-- name: InsertReport :exec

INSERT INTO reports (id, org_id, scan_id, format, content_gz) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scan_id, format) DO UPDATE SET content_gz = EXCLUDED.content_gz
`

type InsertReportParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ScanID    uuid.UUID
	Format    string
	ContentGz []byte
}

// ---------- reports ----------
func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.ID,
		arg.OrgID,
		arg.ScanID,
		arg.Format,
		arg.ContentGz,
	)
	return err
}

const insertScanIssue = `-- name: InsertScanIssue :exec
INSERT INTO scan_issues (scan_id, issue_id, org_id, is_new) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type InsertScanIssueParams struct {
	ScanID  uuid.UUID
	IssueID uuid.UUID
	OrgID   uuid.UUID
	IsNew   bool
}

func (q *Queries) InsertScanIssue(ctx context.Context, arg InsertScanIssueParams) error {
	_, err := q.db.Exec(ctx, insertScanIssue,
		arg.ScanID,
		arg.IssueID,
		arg.OrgID,
		arg.IsNew,
	)
	return err
}

const insertScanTool = `-- name: InsertScanTool :exec
INSERT INTO scan_tools (id, org_id, scan_id, tool_id, name, tool_version, status, duration_ms, findings_count, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertScanToolParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ScanID        uuid.UUID
	ToolID        string
	Name          string
	ToolVersion   string
	Status        string
	DurationMs    int64
	FindingsCount int32
	Error         string
}

func (q *Queries) InsertScanTool(ctx context.Context, arg InsertScanToolParams) error {
	_, err := q.db.Exec(ctx, insertScanTool,
		arg.ID,
		arg.OrgID,
		arg.ScanID,
		arg.ToolID,
		arg.Name,
		arg.ToolVersion,
		arg.Status,
		arg.DurationMs,
		arg.FindingsCount,
		arg.Error,
	)
	return err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (id, org_id, project_id, provider, delivery_id, event, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, delivery_id) DO NOTHING
RETURNING id
`

type InsertWebhookDeliveryParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	ProjectID  uuid.UUID
	Provider   string
	DeliveryID string
	Event      string
	Result     string
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Provider,
		arg.DeliveryID,
		arg.Event,
		arg.Result,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const isScanCanceled = `-- name: IsScanCanceled :one
SELECT status = 'canceled' FROM scans WHERE id = $1
`

func (q *Queries) IsScanCanceled(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isScanCanceled, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lastScanPerProject = `-- name: LastScanPerProject :many
SELECT DISTINCT ON (s.project_id) s.project_id, s.id, s.status, s.gate_result, s.score, s.finished_at, s.summary
FROM scans s WHERE s.org_id = $1 ORDER BY s.project_id, s.queued_at DESC
`

type LastScanPerProjectRow struct {
	ProjectID  uuid.UUID
	ID         uuid.UUID
	Status     string
	GateResult *string
	Score      *int32
	FinishedAt *time.Time
	Summary    json.RawMessage
}

func (q *Queries) LastScanPerProject(ctx context.Context, orgID uuid.UUID) ([]LastScanPerProjectRow, error) {
	rows, err := q.db.Query(ctx, lastScanPerProject, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastScanPerProjectRow{}
	for rows.Next() {
		var i LastScanPerProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Status,
			&i.GateResult,
			&i.Score,
			&i.FinishedAt,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueEvents = `-- name: ListIssueEvents :many
SELECT e.id, e.org_id, e.issue_id, e.user_id, e.kind, e.from_value, e.to_value, e.comment, e.created_at, coalesce(u.email, '') AS user_email FROM issue_events e LEFT JOIN users u ON u.id = e.user_id
WHERE e.org_id = $1 AND e.issue_id = $2 ORDER BY e.created_at
`

type ListIssueEventsParams struct {
	OrgID   uuid.UUID
	IssueID uuid.UUID
}

type ListIssueEventsRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	IssueID   uuid.UUID
	UserID    *uuid.UUID
	Kind      string
	FromValue string
	ToValue   string
	Comment   string
	CreatedAt time.Time
	UserEmail string
}

func (q *Queries) ListIssueEvents(ctx context.Context, arg ListIssueEventsParams) ([]ListIssueEventsRow, error) {
	rows, err := q.db.Query(ctx, listIssueEvents, arg.OrgID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueEventsRow{}
	for rows.Next() {
		var i ListIssueEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.IssueID,
			&i.UserID,
			&i.Kind,
			&i.FromValue,
			&i.ToValue,
			&i.Comment,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, org_id, kind, name, target_enc, nonce, events, created_at FROM notification_channels WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListNotificationChannels(ctx context.Context, orgID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Name,
			&i.TargetEnc,
			&i.Nonce,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgScans = `-- name: ListOrgScans :many
SELECT s.id, s.org_id, s.project_id, s.trigger, s.triggered_by, s.branch, s.commit_sha, s.commit_message, s.commit_author, s.status, s.status_reason, s.partial, s.summary, s.gate_result, s.score, s.new_issues, s.fixed_issues, s.queued_at, s.started_at, s.finished_at, s.cleaned_at, p.name AS project_name, p.slug AS project_slug
FROM scans s JOIN projects p ON p.id = s.project_id
WHERE s.org_id = $1 ORDER BY s.queued_at DESC LIMIT $2
`

type ListOrgScansParams struct {
	OrgID uuid.UUID
	Limit int32
}

type ListOrgScansRow struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ProjectID     uuid.UUID
	Trigger       string
	TriggeredBy   *uuid.UUID
	Branch        string
	CommitSha     string
	CommitMessage string
	CommitAuthor  string
	Status        string
	StatusReason  string
	Partial       bool
	Summary       json.RawMessage
	GateResult    *string
	Score         *int32
	NewIssues     int32
	FixedIssues   int32
	QueuedAt      time.Time
	StartedAt     *time.Time
	FinishedAt    *time.Time
	CleanedAt     *time.Time
	ProjectName   string
	ProjectSlug   string
}

func (q *Queries) ListOrgScans(ctx context.Context, arg ListOrgScansParams) ([]ListOrgScansRow, error) {
	rows, err := q.db.Query(ctx, listOrgScans, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgScansRow{}
	for rows.Next() {
		var i ListOrgScansRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Trigger,
			&i.TriggeredBy,
			&i.Branch,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.Status,
			&i.StatusReason,
			&i.Partial,
			&i.Summary,
			&i.GateResult,
			&i.Score,
			&i.NewIssues,
			&i.FixedIssues,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CleanedAt,
			&i.ProjectName,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIssues = `-- name: ListProjectIssues :many
SELECT id, org_id, project_id, fingerprint, category, severity, title, rule_id, file, start_line, cwe, cve, sources, status, status_reason, detail, first_seen_scan_id, last_seen_scan_id, fixed_in_scan_id, created_at, updated_at FROM issues WHERE org_id = $1 AND project_id = $2 AND ($3::text = '' OR status = $3::text)
ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END,
         file, start_line
LIMIT 500
`

type ListProjectIssuesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) ListProjectIssues(ctx context.Context, arg ListProjectIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listProjectIssues, arg.OrgID, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Fingerprint,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.RuleID,
			&i.File,
			&i.StartLine,
			&i.Cwe,
			&i.Cve,
			&i.Sources,
			&i.Status,
			&i.StatusReason,
			&i.Detail,
			&i.FirstSeenScanID,
			&i.LastSeenScanID,
			&i.FixedInScanID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectScans = `-- name: ListProjectScans :many
SELECT id, org_id, project_id, trigger, triggered_by, branch, commit_sha, commit_message, commit_author, status, status_reason, partial, summary, gate_result, score, new_issues, fixed_issues, queued_at, started_at, finished_at, cleaned_at FROM scans WHERE org_id = $1 AND project_id = $2 ORDER BY queued_at DESC LIMIT $3
`

type ListProjectScansParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Limit     int32
}

func (q *Queries) ListProjectScans(ctx context.Context, arg ListProjectScansParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listProjectScans, arg.OrgID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scan{}
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Trigger,
			&i.TriggeredBy,
			&i.Branch,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.Status,
			&i.StatusReason,
			&i.Partial,
			&i.Summary,
			&i.GateResult,
			&i.Score,
			&i.NewIssues,
			&i.FixedIssues,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CleanedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanIssues = `-- name: ListScanIssues :many
SELECT i.id, i.org_id, i.project_id, i.fingerprint, i.category, i.severity, i.title, i.rule_id, i.file, i.start_line, i.cwe, i.cve, i.sources, i.status, i.status_reason, i.detail, i.first_seen_scan_id, i.last_seen_scan_id, i.fixed_in_scan_id, i.created_at, i.updated_at, si.is_new FROM scan_issues si JOIN issues i ON i.id = si.issue_id
WHERE si.org_id = $1 AND si.scan_id = $2
ORDER BY CASE i.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END,
         i.file, i.start_line
`

type ListScanIssuesParams struct {
	OrgID  uuid.UUID
	ScanID uuid.UUID
}

type ListScanIssuesRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Fingerprint     string
	Category        string
	Severity        string
	Title           string
	RuleID          string
	File            string
	StartLine       int32
	Cwe             []string
	Cve             []string
	Sources         []string
	Status          string
	StatusReason    string
	Detail          json.RawMessage
	FirstSeenScanID *uuid.UUID
	LastSeenScanID  *uuid.UUID
	FixedInScanID   *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	IsNew           bool
}

func (q *Queries) ListScanIssues(ctx context.Context, arg ListScanIssuesParams) ([]ListScanIssuesRow, error) {
	rows, err := q.db.Query(ctx, listScanIssues, arg.OrgID, arg.ScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScanIssuesRow{}
	for rows.Next() {
		var i ListScanIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Fingerprint,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.RuleID,
			&i.File,
			&i.StartLine,
			&i.Cwe,
			&i.Cve,
			&i.Sources,
			&i.Status,
			&i.StatusReason,
			&i.Detail,
			&i.FirstSeenScanID,
			&i.LastSeenScanID,
			&i.FixedInScanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanTools = `-- name: ListScanTools :many
SELECT id, org_id, scan_id, tool_id, name, tool_version, status, duration_ms, findings_count, error FROM scan_tools WHERE org_id = $1 AND scan_id = $2 ORDER BY tool_id
`

type ListScanToolsParams struct {
	OrgID  uuid.UUID
	ScanID uuid.UUID
}

func (q *Queries) ListScanTools(ctx context.Context, arg ListScanToolsParams) ([]ScanTool, error) {
	rows, err := q.db.Query(ctx, listScanTools, arg.OrgID, arg.ScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTool{}
	for rows.Next() {
		var i ScanTool
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScanID,
			&i.ToolID,
			&i.Name,
			&i.ToolVersion,
			&i.Status,
			&i.DurationMs,
			&i.FindingsCount,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupWebhookProject = `-- name: LookupWebhookProject :one
SELECT l.id::uuid AS id, l.org_id::uuid AS org_id, l.provider::text AS provider, l.branches::text[] AS branches,
       coalesce(l.webhook_secret_enc, ''::bytea)::bytea AS webhook_secret_enc,
       coalesce(l.webhook_secret_nonce, ''::bytea)::bytea AS webhook_secret_nonce,
       l.archived::bool AS archived
FROM scanx_lookup_webhook_project($1::uuid) AS l
`

type LookupWebhookProjectRow struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	Provider           string
	Branches           []string
	WebhookSecretEnc   []byte
	WebhookSecretNonce []byte
	Archived           bool
}

func (q *Queries) LookupWebhookProject(ctx context.Context, projectID uuid.UUID) (LookupWebhookProjectRow, error) {
	row := q.db.QueryRow(ctx, lookupWebhookProject, projectID)
	var i LookupWebhookProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Branches,
		&i.WebhookSecretEnc,
		&i.WebhookSecretNonce,
		&i.Archived,
	)
	return i, err
}

const markMissingIssuesFixed = `-- name: MarkMissingIssuesFixed :execrows
UPDATE issues SET status = 'fixed', fixed_in_scan_id = $1::uuid, updated_at = now()
WHERE project_id = $2::uuid AND status = 'open'
  AND id NOT IN (SELECT issue_id FROM scan_issues WHERE scan_id = $1::uuid)
`

type MarkMissingIssuesFixedParams struct {
	ScanID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) MarkMissingIssuesFixed(ctx context.Context, arg MarkMissingIssuesFixedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingIssuesFixed, arg.ScanID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectsMissingCredentials = `-- name: ProjectsMissingCredentials :many
SELECT p.id, p.org_id, p.name, p.slug, p.repo_url, p.provider, p.auth_mode, p.branches, p.settings, p.schedule_cron, p.created_at, p.updated_at, p.archived_at, p.webhook_secret_enc, p.webhook_secret_nonce, p.fail_on, p.scan_history FROM projects p
WHERE p.webhook_secret_enc IS NULL
   OR NOT EXISTS (SELECT 1 FROM ssh_keys k WHERE k.project_id = p.id AND k.status = 'active')
`

// Projects created before deploy keys / webhook secrets existed.
func (q *Queries) ProjectsMissingCredentials(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, projectsMissingCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.RepoUrl,
			&i.Provider,
			&i.AuthMode,
			&i.Branches,
			&i.Settings,
			&i.ScheduleCron,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.WebhookSecretEnc,
			&i.WebhookSecretNonce,
			&i.FailOn,
			&i.ScanHistory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSSHKeys = `-- name: RetireSSHKeys :exec
UPDATE ssh_keys SET status = 'retiring', retired_at = now()
WHERE org_id = $1 AND project_id = $2 AND status = 'active'
`

type RetireSSHKeysParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RetireSSHKeys(ctx context.Context, arg RetireSSHKeysParams) error {
	_, err := q.db.Exec(ctx, retireSSHKeys, arg.OrgID, arg.ProjectID)
	return err
}

const setScanCommit = `-- name: SetScanCommit :exec
UPDATE scans SET commit_sha = $2, commit_message = $3, commit_author = $4 WHERE id = $1
`

type SetScanCommitParams struct {
	ID            uuid.UUID
	CommitSha     string
	CommitMessage string
	CommitAuthor  string
}

func (q *Queries) SetScanCommit(ctx context.Context, arg SetScanCommitParams) error {
	_, err := q.db.Exec(ctx, setScanCommit,
		arg.ID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.CommitAuthor,
	)
	return err
}

const setScanStatus = `-- name: SetScanStatus :exec
UPDATE scans SET status = $2, status_reason = $3,
    started_at = CASE WHEN $2 = 'cloning' THEN coalesce(started_at, now()) ELSE started_at END
WHERE id = $1
`

type SetScanStatusParams struct {
	ID           uuid.UUID
	Status       string
	StatusReason string
}

func (q *Queries) SetScanStatus(ctx context.Context, arg SetScanStatusParams) error {
	_, err := q.db.Exec(ctx, setScanStatus, arg.ID, arg.Status, arg.StatusReason)
	return err
}

const setWebhookSecret = `-- name: SetWebhookSecret :exec

UPDATE projects SET webhook_secret_enc = $3, webhook_secret_nonce = $4, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type SetWebhookSecretParams struct {
	OrgID              uuid.UUID
	ID                 uuid.UUID
	WebhookSecretEnc   []byte
	WebhookSecretNonce []byte
}

// ---------- project scan settings ----------
func (q *Queries) SetWebhookSecret(ctx context.Context, arg SetWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, setWebhookSecret,
		arg.OrgID,
		arg.ID,
		arg.WebhookSecretEnc,
		arg.WebhookSecretNonce,
	)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues SET status = $3, status_reason = $4, updated_at = now() WHERE org_id = $1 AND id = $2
`

type UpdateIssueStatusParams struct {
	OrgID        uuid.UUID
	ID           uuid.UUID
	Status       string
	StatusReason string
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.Exec(ctx, updateIssueStatus,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.StatusReason,
	)
	return err
}

const updateProjectScanSettings = `-- name: UpdateProjectScanSettings :exec
UPDATE projects SET fail_on = $3, scan_history = $4, updated_at = now() WHERE org_id = $1 AND id = $2
`

type UpdateProjectScanSettingsParams struct {
	OrgID       uuid.UUID
	ID          uuid.UUID
	FailOn      string
	ScanHistory bool
}

func (q *Queries) UpdateProjectScanSettings(ctx context.Context, arg UpdateProjectScanSettingsParams) error {
	_, err := q.db.Exec(ctx, updateProjectScanSettings,
		arg.OrgID,
		arg.ID,
		arg.FailOn,
		arg.ScanHistory,
	)
	return err
}

const upsertIssue = `-- name: UpsertIssue :one

INSERT INTO issues (id, org_id, project_id, fingerprint, category, severity, title, rule_id, file, start_line,
                    cwe, cve, sources, detail, first_seen_scan_id, last_seen_scan_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15)
ON CONFLICT (project_id, fingerprint) DO UPDATE SET
    severity = EXCLUDED.severity, title = EXCLUDED.title, rule_id = EXCLUDED.rule_id, file = EXCLUDED.file,
    start_line = EXCLUDED.start_line, cwe = EXCLUDED.cwe, cve = EXCLUDED.cve, sources = EXCLUDED.sources,
    detail = EXCLUDED.detail, last_seen_scan_id = EXCLUDED.last_seen_scan_id,
    status = CASE WHEN issues.status = 'fixed' THEN 'open' ELSE issues.status END,
    fixed_in_scan_id = CASE WHEN issues.status = 'fixed' THEN NULL ELSE issues.fixed_in_scan_id END,
    updated_at = now()
RETURNING id, (xmax = 0) AS inserted, status
`

type UpsertIssueParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Fingerprint     string
	Category        string
	Severity        string
	Title           string
	RuleID          string
	File            string
	StartLine       int32
	Cwe             []string
	Cve             []string
	Sources         []string
	Detail          json.RawMessage
	FirstSeenScanID *uuid.UUID
}

type UpsertIssueRow struct {
	ID       uuid.UUID
	Inserted bool
	Status   string
}

// ---------- issues ----------
// Re-opens a previously fixed issue that reappears; user decisions
// (false_positive, accepted_risk, wont_fix) are kept.
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (UpsertIssueRow, error) {
	row := q.db.QueryRow(ctx, upsertIssue,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Fingerprint,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.RuleID,
		arg.File,
		arg.StartLine,
		arg.Cwe,
		arg.Cve,
		arg.Sources,
		arg.Detail,
		arg.FirstSeenScanID,
	)
	var i UpsertIssueRow
	err := row.Scan(&i.ID, &i.Inserted, &i.Status)
	return i, err
}
