// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, mfa_pending, active_org_id, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	TokenHash   []byte
	MfaPending  bool
	ActiveOrgID *uuid.UUID
	Ip          string
	UserAgent   string
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.MfaPending,
		arg.ActiveOrgID,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions WHERE user_id = $1 AND id = $2
`

type DeleteUserSessionParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.UserID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID uuid.UUID
	KeepID uuid.UUID
}

func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.KeepID)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT s.id, s.user_id, s.mfa_pending, s.active_org_id, s.created_at, s.last_seen_at, s.expires_at,
       u.email, u.name, u.is_superadmin, u.totp_enabled, u.locale, u.locked_until
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionByHashRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	MfaPending   bool
	ActiveOrgID  *uuid.UUID
	CreatedAt    time.Time
	LastSeenAt   time.Time
	ExpiresAt    time.Time
	Email        string
	Name         string
	IsSuperadmin bool
	TotpEnabled  bool
	Locale       string
	LockedUntil  *time.Time
}

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaPending,
		&i.ActiveOrgID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.IsSuperadmin,
		&i.TotpEnabled,
		&i.Locale,
		&i.LockedUntil,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, ip, user_agent, created_at, last_seen_at, mfa_pending
FROM sessions WHERE user_id = $1 AND expires_at > now() ORDER BY last_seen_at DESC
`

type ListUserSessionsRow struct {
	ID         uuid.UUID
	Ip         string
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	MfaPending bool
}

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.MfaPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionActiveOrg = `-- name: SetSessionActiveOrg :exec
UPDATE sessions SET active_org_id = $2 WHERE id = $1
`

type SetSessionActiveOrgParams struct {
	ID          uuid.UUID
	ActiveOrgID *uuid.UUID
}

func (q *Queries) SetSessionActiveOrg(ctx context.Context, arg SetSessionActiveOrgParams) error {
	_, err := q.db.Exec(ctx, setSessionActiveOrg, arg.ID, arg.ActiveOrgID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
