// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens_audit_settings.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, org_id, user_id, project_id, name, token_prefix, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAPITokenParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	UserID      *uuid.UUID
	ProjectID   *uuid.UUID
	Name        string
	TokenPrefix string
	TokenHash   []byte
	Scopes      []string
	ExpiresAt   *time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.Exec(ctx, createAPIToken,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM instance_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, org_id, user_id, action, target_type, target_id, ip, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ID         uuid.UUID
	OrgID      *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	TargetType string
	TargetID   string
	Ip         string
	Metadata   json.RawMessage
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.Metadata,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.org_id, a.user_id, a.action, a.target_type, a.target_id, a.ip, a.metadata, a.created_at,
       coalesce(u.email, '') AS user_email
FROM audit_logs a LEFT JOIN users u ON u.id = a.user_id
WHERE a.org_id = $1
ORDER BY a.created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	OrgID  *uuid.UUID
	Limit  int32
	Offset int32
}

type ListAuditLogsRow struct {
	ID         uuid.UUID
	OrgID      *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	TargetType string
	TargetID   string
	Ip         string
	Metadata   json.RawMessage
	CreatedAt  time.Time
	UserEmail  string
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, org_id, name, token_prefix, scopes, last_used_at, expires_at, created_at
FROM api_tokens WHERE org_id = $1 AND user_id = $2 AND revoked_at IS NULL ORDER BY created_at DESC
`

type ListUserAPITokensParams struct {
	OrgID  uuid.UUID
	UserID *uuid.UUID
}

type ListUserAPITokensRow struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	TokenPrefix string
	Scopes      []string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	CreatedAt   time.Time
}

func (q *Queries) ListUserAPITokens(ctx context.Context, arg ListUserAPITokensParams) ([]ListUserAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAPITokensRow{}
	for rows.Next() {
		var i ListUserAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSetup = `-- name: LockSetup :exec
SELECT pg_advisory_xact_lock(726200)
`

// Serializes first-admin creation across concurrent requests.
func (q *Queries) LockSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSetup)
	return err
}

const lookupAPIToken = `-- name: LookupAPIToken :one
SELECT l.id::uuid AS id, l.org_id::uuid AS org_id,
       coalesce(l.user_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS user_id, coalesce(l.project_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS project_id,
       l.scopes::text[] AS scopes,
       coalesce(l.expires_at, '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS expires_at,
       coalesce(l.revoked_at, '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS revoked_at
FROM scanx_lookup_api_token($1::bytea) AS l
`

type LookupAPITokenRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Scopes    []string
	ExpiresAt time.Time
	RevokedAt time.Time
}

// Nullable columns are coalesced to zero values (zero = absent).
func (q *Queries) LookupAPIToken(ctx context.Context, tokenHash []byte) (LookupAPITokenRow, error) {
	row := q.db.QueryRow(ctx, lookupAPIToken, tokenHash)
	var i LookupAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ProjectID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUserAPIToken = `-- name: RevokeUserAPIToken :execrows
UPDATE api_tokens SET revoked_at = now() WHERE org_id = $1 AND user_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeUserAPITokenParams struct {
	OrgID  uuid.UUID
	UserID *uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) RevokeUserAPIToken(ctx context.Context, arg RevokeUserAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserAPIToken, arg.OrgID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO instance_settings (key, value, updated_at) VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSettingParams struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
