// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, password_hash, is_superadmin, locale)
VALUES ($1, lower($6), $2, $3, $4, $5)
RETURNING id, email, name, password_hash, totp_secret_enc, totp_nonce, totp_enabled, is_superadmin, locked_until, failed_logins, created_at, last_login_at, locale
`

type CreateUserParams struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
	IsSuperadmin bool
	Locale       string
	Email        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.IsSuperadmin,
		arg.Locale,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpNonce,
		&i.TotpEnabled,
		&i.IsSuperadmin,
		&i.LockedUntil,
		&i.FailedLogins,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Locale,
	)
	return i, err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users SET totp_enabled = false, totp_secret_enc = NULL, totp_nonce = NULL WHERE id = $1
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE users SET totp_enabled = true WHERE id = $1 AND totp_secret_enc IS NOT NULL
`

func (q *Queries) EnableUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableUserTOTP, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, totp_secret_enc, totp_nonce, totp_enabled, is_superadmin, locked_until, failed_logins, created_at, last_login_at, locale FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpNonce,
		&i.TotpEnabled,
		&i.IsSuperadmin,
		&i.LockedUntil,
		&i.FailedLogins,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Locale,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, totp_secret_enc, totp_nonce, totp_enabled, is_superadmin, locked_until, failed_logins, created_at, last_login_at, locale FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpNonce,
		&i.TotpEnabled,
		&i.IsSuperadmin,
		&i.LockedUntil,
		&i.FailedLogins,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Locale,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, totp_secret_enc, totp_nonce, totp_enabled, is_superadmin, locked_until, failed_logins, created_at, last_login_at, locale FROM users ORDER BY created_at LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.TotpSecretEnc,
			&i.TotpNonce,
			&i.TotpEnabled,
			&i.IsSuperadmin,
			&i.LockedUntil,
			&i.FailedLogins,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users
SET failed_logins = failed_logins + 1,
    locked_until = CASE WHEN failed_logins + 1 >= $2::int
                        THEN now() + make_interval(mins => $3::int)
                        ELSE locked_until END
WHERE id = $1
RETURNING failed_logins, locked_until
`

type RecordLoginFailureParams struct {
	ID          uuid.UUID
	Threshold   int32
	LockMinutes int32
}

type RecordLoginFailureRow struct {
	FailedLogins int32
	LockedUntil  *time.Time
}

// Increments the failure counter and locks the account once the threshold is reached.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.ID, arg.Threshold, arg.LockMinutes)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLogins, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users SET failed_logins = 0, locked_until = NULL, last_login_at = now() WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users SET totp_secret_enc = $2, totp_nonce = $3, totp_enabled = false WHERE id = $1
`

type SetUserTOTPSecretParams struct {
	ID            uuid.UUID
	TotpSecretEnc []byte
	TotpNonce     []byte
}

func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setUserTOTPSecret, arg.ID, arg.TotpSecretEnc, arg.TotpNonce)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name = $2, locale = $3 WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID     uuid.UUID
	Name   string
	Locale string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Name, arg.Locale)
	return err
}
